spring:
  # 数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/smart-medicine?serverTimezone=Hongkong&useAffectedRows=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 邮件配置
  mail:
    username: 3628877370@qq.com
    password: ndhazhbjlqjpchdh
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    valid: 5
    title: "寻药就医 - 用户认证"
    template: "您的动态验证码为：<strong style='color: red'>%s</strong>，%d分钟内有效，若非本人操作，请勿泄露。"
# 日志配置
logging:
  level:
    world.world.test.dao.mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云通义千问配置
ai-key: sk-dd38b4d24d60443daff7519f1e0ea132


file:
  upload-path: /uploads
server:
  port: 8082